version: '3'
services:
  db:
    image: postgres
    container_name: microservicetestproject-db-1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword

  web:
    build: .
    container_name: microservicetestproject-web-1
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000